### ISSUE TITLE
error : 403 disallowed_useragent while authenticating with google using azure services in iOS

### ISSUE THREAD

**Issue by Quilbeast** [Azure/azure-mobile-apps-net-client#263]
Google stopped supporting webviews for authentication:
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

This package uses webviews to connect to google in iOS, because of this, google authentication in iOS is not working.

**Comment by adrianhall** [comment]
We are working on this.  In the interim, set up Client-Flow for Google.

**Comment by Quilbeast** [comment]
I'm trying to implement the client flow now. I came up to the point that I have to login in azure with the access_token and id_token from google, but I get an exception (Unauthorized):

` var zumoPayload = new JObject();
 zumoPayload["access_token"] = SignIn.SharedInstance.CurrentUser.Authentication.AccessToken;
 zumoPayload["id_token"] = SignIn.SharedInstance.CurrentUser.Authentication.IdToken;

 var user = await AanvraagManager.DefaultManager.CurrentClient.LoginAsync("google", zumoPayload);`

 Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The request could not be completed.  (Unauthorized)

Both the access_token and the id_token are correctly filled.

Am I doing something wrong?

**Comment by mattchenderson** [comment]
Per the [documentation for the Google client flow on iOS](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#a-namegoogle-sdkahow-to-authenticate-users-with-the-google-sign-in-sdk-for-ios), the payload is expected to be an ID token and authorization code. This documentation does need to be updated for some of the Firebase SDKs that Google is using now, but hopefully that helps.

**Comment by Quilbeast** [comment]
Thanks for the response. I just fixed the issue. The problem was that for client flow I had to create a client_id and for azure I had to create a client id (at console.google.com). When I posted my authorization token to Azure it gave me the response: 

JWT validation failed: IDX10214: Audience validation failed. Audiences: '[ClientID1].apps.googleusercontent.com'. Did not match:  validationParameters.ValidAudience: '[ClientID2].apps.googleusercontent.com' or validationParameters.ValidAudiences: 'null'.

To fix this issue I ended up editing the azure config file at https://resources.azure.com ( subscriptions/ Pay per use / resourceGroups / [my project] / providers / Microsoft.Web / sites / [my project] / config / authsettings / allowedAudiences)

I hope this helps for anyone else struggeling with this problem. This is really poorly documented.

**Comment by bbougot** [comment]
Still the same issue using the Azure Mobile Apps Client. It should work out of the box.

**Comment by felixkm** [comment]
In case it is still a problem, [this blog post](https://cloudrail.com/solving-disallowed_useragent-for-google-services/) might help.

**Comment by ntrogh** [comment]
@adrianhall problem is fixed in UWP on v3.1.0 but still persists for iOS and Android. Any update on timing for a fix?

**Comment by adrianhall** [comment]
For iOS and Android, we use Xamarin.Auth; there is nothing in the main library that would cause an issue.  Have you updated Xamarin.Auth?

**Comment by ntrogh** [comment]
There's an open issue on Xamarin.Auth specific to [this](https://github.com/xamarin/Xamarin.Auth/issues/137)

**Comment by moljac** [comment]
@ntrogh @adrianhall 
It is still open, so that users can read discussion on how to setup (most of them do not check closed issues). Xamarin.Auth provides support for  Native UI (CustomTabs and SFSafariViewContoller) in nuget v. 1.4.x, but the API was slightly changed. 
In 1.5.0-alpha-* there is even Xamarin.Forms support.

Adrian, I tried to ping Paul Batum on Xamarin private slack team regarding Xamarin.Auth update and feedback (I found his name here and guys on Xamarin Components team told me to try to ping him).

**Comment by adrianhall** [comment]
I am no longer with Microsoft, so cannot assist here.

**Comment by randeep80** [comment]
any update here for Xamarin Forms

**Comment by filoe** [comment]
Still having issues with this.
